
package org.cryptobiotic.rla.model

/**
 * A cast vote record contains information about a single ballot, either
 * imported from a tabulator export file or generated by auditors.
 *
 * @author Daniel M. Zimmerman <dmz></dmz>@freeandfair.us>
 * @version 1.0.0
 */

data class CVRContestInfo(
    val contest: Contest,
    val comment: String,
    val countyId: Long,
    val choices: List<String>,
) {
    internal var consensus: ConsensusValue? = null

    enum class ConsensusValue { YES, NO }
}
